corner-radius = 15;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'mpv'",
  "class_g = 'XWinWrap'"
];

shadow = false;
shadow-radius = 10;
shadow-opacity = 0.4;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-exclude = [
  "window_type = 'dock'",
  "class_g = 'qtile'",
  "class_g = 'mpv'",
  "class_g = 'XWinWrap'",
  "class_g = 'ulauncher'",
  "class_g = 'ulauncher-toggle'",
  "class_g = 'Ulauncher'",
  "window_type = 'desktop'"
];

opacity-rule = [
  "99:name *= 'i3lock'"
];

blur-background = false;
blur-method = "dual_kawase";
blur-strength = 8;
blur-background-exclude = [
  "class_g = 'ulauncher'",
  "class_g = 'ulauncher-toggle'",
  "class_g = 'Ulauncher'"
];

unredir-if-possible = true;
mark-ovredir-focused = true;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

backend = "glx";
vsync = true;

glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = false;
transparent-clipping = false;

wintypes :
{
  dock = { shadow = false clip-shadow-above = true }
  dnd = { shadow = false }
  tooltip = { shadow = false }
};